# Generated by Django 3.2.13 on 2022-12-11 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(default='gmail.com', max_length=254)),
                ('age', models.IntegerField()),
                ('B_Time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yoga_enroll.batch')),
                ('M_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yoga_enroll.month')),
            ],
        ),
    ]
