# Generated by Django 3.2.13 on 2022-12-11 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_enroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='B_Time',
            new_name='Batch',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='M_Name',
            new_name='Month',
        ),
    ]
